#! /bin/bash
# #
# # Build Curator Tool
# cd /gitroot/libsbgn && ant \
# && cd /gitroot/CuratorTool/ant \
# && ant -buildfile ReactomeJar.xml \
# && ant -buildfile CuratorToolBuild.xml \
# # ---------------------------------------------------------------------------------------
# # Build Pathway Exchange
# && cd /gitroot/Pathway-Exchange \
# && mvn install:install-file -Dfile=/gitroot/libsbgn/dist/org.sbgn.jar -DartifactId=sbgn -DgroupId=org.sbgn -Dpackaging=jar -Dversion=milestone2 \
# && mvn install:install-file -Dfile=./lib/celldesigner/celldesigner.jar -DgroupId=celldesigner -DartifactId=celldesigner -Dversion=UNKNOWN_VERSION -Dpackaging=jar \
# && mvn install:install-file -Dfile=./lib/protege/arq.jar -DgroupId=com.hp.hpl.jena -DartifactId=arq -Dpackaging=jar -Dversion=UNKNOWN_VERSION \
# && mvn install:install-file -Dfile=./lib/protege/protege.jar -Dpackaging=jar -DgroupId=edu.stanford.protege -DartifactId=protege -Dversion=UNKNOWN_VERSION \
# && mvn install:install-file -Dfile=./lib/protege/protege-owl.jar -Dversion=3.2 -DgroupId=edu.stanford.smi.protege -DartifactId=protege-owl -Dpackaging=jar \
# && mvn install:install-file -Dfile=lib/sbml/jsbml-0.8-rc1-with-dependencies.jar -DgroupId=org.sbml -DartifactId=jsbml -Dversion=0.8-rc1 -Dpackaging=jar \
# && mvn install:install-file -Dfile=./lib/sbml/libsbmlj.jar -DgroupId=org.sbml -DartifactId=libsbml -Dpackaging=jar -Dversion=0.8-rc1 \
# && pwd && mvn compile package install \
# # ---------------------------------------------------------------------------------------
# # Build RESTfulAPI
# && cd /gitroot/RESTfulAPI/ -lht \
# && mvn install:install-file -Dfile=/gitroot/CuratorTool/reactome.jar -DartifactId=Reactome -DgroupId=org.reactome -Dpackaging=jar -Dversion=UNKNOWN_VERSION \
# && pwd && mvn package \
# # ---------------------------------------------------------------------------------------
# # Build Pathway Browser
# && cd /gitroot/browser && mvn package \
# && cd /gitroot/diagram-exporter && mvn install \
# # ---------------------------------------------------------------------------------------
# # Build Content-service
# # cd /gitroot/content-service && mvn package && \
# ---------------------------------------------------------------------------------------
# Analysis Tools requires core and service, building and installing core first
cd /gitroot/AnalysisTools/Core && mvn package install \
&& echo "Follpwing files were generated in Core/target" \
&& ls -a /gitroot/AnalysisTools/Core/target/ \
#
# Build AnalysisTools service
cd /gitroot/AnalysisTools/Service && mvn package \
# ---------------------------------------------------------------------------------------
# Copy war files generated by above builds to webapps which is shared with host
#
# && cp /gitroot/browser/target/PathwayBrowser*.war /webapps/PathwayBrowser.war \
# && cp /gitroot/content-service/target/ContentService*.war /webapps/ContentService.war \
# && cp /gitroot/AnalysisTools/Service/target/analysis-service*.war /webapps/analysis-service.war \
# && cp /gitroot/RESTfulAPI/target/ReactomeRESTfulAPI*.war /webapps/ReactomeRESTfulAPI.war
cp /gitroot/AnalysisTools/Service/target/analysis-service*.war /webapps/