FROM perl:5.20
# COPY . /usr/local/bin/perl
# WORKDIR /usr/local/bin/perl

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y libapache2-mod-perl2 graphviz libossp-uuid-perl libsoap-lite-perl libical-dev libical1a libapr1
RUN cpan install CPAN
RUN cpan install App::cpanminus
RUN cpanm install --notest --quiet File::Which File::Slurp File::HomeDir File::HomeDir \
	WWW::SearchResult WWW::Search Search::Query \
	URI::Encode \
	Font::TTF \
	RTF::Writer \
	Try::Tiny \
	IO::Capture \
	Log::Log4perl \
	JSON::XS JSON::PP \
	PDF::API2 \
	namespace \
	Test \
	Email::Valid \
	DateTime::TimeZone DateTime::Locale DateTime::Format::Strptime DateTime::Format::DateParse DateTime::Duration DateTime::Infinite  DateTime::Helpers DateTime::LeapSecond \
	Data::Dump Data::Transformer Data::UUID  \
	HTML::Entities HTML::LinkExtor HTML::Parser HTML::HeadParser HTML::PullParser HTML::Filter HTML::TokeParser \
	Tk \
	Term::ReadKey \
	Ace \
	Variable::Magic \
	XML::Parser XML::LibXSLT XML::LibXML \
	Attribute::Params::Validate \
	Algorithm::Diff::XS \
	File::FcntlLock \
	Net::SSLeay Net::SSL Net::Daemon \
	Type::Tiny::XS \
	YAML \
	Convert::Binary::C Convert::Binary::C::Cached \
	IPC::ShareLite \
	IO::Tty::Constant IO::Tty IO::Pty \
	Lexical::SealRequireHints \
	bareword::filehandles \
	Crypt::SSLeay \
	Bit::Vector \
	Text::CharWidth Text::Iconv Text::Soundex \
	Locale::gettext \
	Devel \
	List::MoreUtils \
	GFF::Filehandle \
	Date::Calc::XS \
	DBD \
	BSD::Resource \
	Unicode::Map \
	Package::Stash::XS \
	Params::Validate Params::Validate::Constants Params::Validate::PP Params::Validate::XS \
	DBI \
	Moose \
	Exporter \
	Moo \
	MLDBM::Serializer \
	Class::Singleton \
	URI \
	Term::UI Term::UI::History \
	Task::Weaken \
	PostScript::Metrics PostScript::TextBlock PostScript::Document PostScript::Elements  \
	Eval::TypeTiny \
	XMLRPC XMLRPC::Transport::HTTP XMLRPC::Transport::TCP XMLRPC::Transport::POP3 \
	Module::Build \
	Role::Tiny Role::Tiny::With \
	Spreadsheet::WriteExcel Spreadsheet::ParseExcel \
	Algorithm::Munkres Algorithm::DiffOld Algorithm::C3 Algorithm::Merge \
	Reply::Plugin::TypeTiny \
	File::Listing File::Rename File::Slurp::Tiny File::Copy::Recursive \
	Method::Generate::Accessor Method::Generate::DemolishAll Method::Generate::Constructor Method::Generate::BuildAll Method::Inliner \
	Log::Message \
	CGI \
	Cache \
	Data \
	Dist::CheckConflicts \
	Time::Zone \
	Types::Standard Types::Common::String Types::Common::Numeric Types::TypeTiny \
	Font::TTF Font::TTFMetrics \
	Archive::Extract \
	Git \
	Encode \
	Perl4::CoreLibs \
	Import::Into \
	Text::Unidecode Text::WrapI18N Text::Template \
	Heap::Elem Heap::Fibonacci Heap071::Elem Heap071::Fibonacci  \
	SVG \
	Math::Spline Math::Derivative \
	Locale::RecodeData Locale::TextDomain Locale::Recode Locale::gettext_dumb Locale::Util Locale::gettext_pp \
	MRO::Compat \
	inc \
	Array::Compare \
	List::AllUtils List::MoreUtils \
	LWP \
	Error \
	Statistics::Descriptive \
	Date \
	MIME::WordDecoder MIME::Entity MIME::Body MIME::Parser MIME::Words MIME::Tools MIME::Decoder MIME::Head \
	Pod::Readme Pod::LaTeX \
	Mail::Send Mail::Header Mail::Field Mail::Address Mail::Internet Mail::Filter Mail::Util Mail::Mailer Mail::Cap \
	Regexp::Common \
	Package \
	Graph \
	Tree \
	Try \
	Parse::RecDescent \
	Sort::Naturally \
	Digest \
	Authen::SASL \
	GraphViz \
	Software::License \
	Set::Scalar
	# APR \
	# Net \
	# Win32::DBIODBC \
	# Apache \
	# SOAP \
	# Debconf \
	# Dselect::Ftp \
	# Dpkg \
	# share \
	# Bio \
	# Bundle::Apache2 \
	# MyTest::Util \
	# Sub \
	# ModPerl \


#RUN apt-get update
#RUN apt-get install -y libfile-which-perl libfile-slurp-unicode-perl libfile-homedir-perl

#CMD [ "perl", "./script.pl" ]
